### ISSUE TITLE
Bug en el fichero 1.md

### ISSUE THREAD

**Issue by vrsanchez99** [perezrecjorge/Richard-Stallman-y-la-historia-jamas-contada.#1]
Ambos links  de https://github.com/perezrecjorge/Richard-Stallman-y-la-historia-jam-s-contada./blob/master/1.md llevan a otros ficheros que solo ponen "hola".

**Comment by perezrecjorge** [comment]
Muchas gracias por colaborar en el proyecto.

Le informo que la historia no esta terminada, nuestro equipo esta poniendo todo su esfuerzo en acabarlo lo antes posible. Gracias.

Att. El equipo de trabajo (de un solo miembro).

**Comment by perezrecjorge** [comment]
Le informo que ya estaba terminado.

Att. Jorge Pérez.
